version: '3.8'

services:
  app:
    build: .
    container_name: trabajador_api
    restart: unless-stopped
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/trabajadores
    depends_on:
      - mongo
    networks:
      - trabajador_net

  mongo:
    image: mongo:7
    container_name: trabajador_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - trabajador_net

networks:
  trabajador_net:
    driver: bridge

volumes:
  mongo_data:
